"""Portable TLS detail codes, read from the header that defines them.

Since #813 every TLS backend reports the same `enum SolidSyslogTlsStreamErrors`
values, which is what lets one scenario assert the same number on all four BDD
lanes. Feature files name a code; this maps the name to the number the target
prints.

The table is parsed from Core/Interface/SolidSyslogTlsStreamErrors.h rather than
generated by CMake, because unlike the tunables mirror nothing about it varies
with build configuration. Parsing it here also means no extra artefact has to be
carried into the BDD jobs.

A misparse cannot pass silently: expected values come from here and actual ones
from the running target, so a shifted member fails the scenario rather than
passing it. The checks below turn the two mistakes that would otherwise be
confusing into an import-time failure with a clear message.
"""

import pathlib
import re

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
_HEADER = _REPO_ROOT / "Core" / "Interface" / "SolidSyslogTlsStreamErrors.h"

_PREFIX = "SOLIDSYSLOG_TLS_STREAM_ERROR_"
_BLOCK = re.compile(r"enum\s+SolidSyslogTlsStreamErrors\s*\{(.*?)\}\s*;", re.DOTALL)
_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
_MEMBER = re.compile(rf"\b{_PREFIX}([A-Z0-9_]+)\b\s*(?:=\s*(\d+))?")


def _parse(header_text):
    block = _BLOCK.search(header_text)
    if block is None:
        raise RuntimeError(f"No enum SolidSyslogTlsStreamErrors in {_HEADER}")

    codes = {}
    nextValue = 0
    for name, explicit in _MEMBER.findall(_COMMENT.sub(" ", block.group(1))):
        if explicit:
            nextValue = int(explicit)
        codes[name] = nextValue
        nextValue += 1

    # A truncated block match yields members but no _MAX, which would otherwise
    # give every code a plausible-looking wrong value.
    if "MAX" not in codes:
        raise RuntimeError(f"{_PREFIX}MAX missing from {_HEADER}")

    # E39 requires appending before _MAX, never after it: a member added after
    # _MAX renumbers nothing here but means the enum no longer bounds itself.
    lastName = list(codes)[-1]
    if lastName != "MAX":
        raise RuntimeError(
            f"{_PREFIX}{lastName} is declared after {_PREFIX}MAX in {_HEADER}; "
            f"codes are appended before _MAX so the enum keeps bounding itself"
        )
    return codes


TLS_ERROR_CODES = _parse(_HEADER.read_text(encoding="utf-8"))


def tls_error_code(name):
    """The number a target prints for a code named in a feature file.

    Accepts the short name ("PEER_CERTIFICATE_EXPIRED") so feature files read
    as the contract rather than as C identifiers.
    """
    shortName = name.strip().upper()
    if shortName.startswith(_PREFIX):
        shortName = shortName[len(_PREFIX):]
    if shortName not in TLS_ERROR_CODES:
        known = ", ".join(sorted(TLS_ERROR_CODES))
        raise KeyError(f"Unknown TLS detail code {name!r}. Known codes: {known}")
    return TLS_ERROR_CODES[shortName]
